# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow  run is made up of one or more jobs that can run sequentially or in parallel
jobs:       
    robot_test:
      runs-on: ubuntu-latest
      name: Run Robot Framework Tests
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Debug
          run: |
              ls -R . && ls -R ${{github.workspace}} && pwd
        - name: Robot Framework run tests
          uses: joonvena/robotframework-docker-action@v0.1
          env:
            BROWSER: firefox
            ROBOT_TESTS_DIR: ${{github.workspace}}/e2e/tests
            ROBOT_REPORTS_DIR: /home/runner/work/finalLessons/reports
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: /home/runner/work/finalLessons/reports
    deploy_to_heroku:
        runs-on: ubuntu-latest
        name: Deploy to Heroku
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Deploy
              uses: akhileshns/heroku-deploy@v3.5.6
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                  heroku_email: ${{secrets.HEROKU_EMAIL}}

